#!/bin/bash

# Vercel Storage Setup Script for LLMos
# This script helps you set up Vercel Blob + KV storage

set -e

echo "================================================"
echo "🚀 LLMos Vercel Storage Setup"
echo "================================================"
echo ""

# Check if Vercel CLI is installed
if ! command -v vercel &> /dev/null; then
    echo "❌ Vercel CLI not found. Installing..."
    npm install -g vercel
    echo "✅ Vercel CLI installed"
else
    echo "✅ Vercel CLI found"
fi

echo ""
echo "================================================"
echo "Step 1: Link to Vercel Project"
echo "================================================"
echo ""
echo "This will connect this directory to your Vercel project."
echo "If you haven't deployed yet, run 'vercel' first to create a project."
echo ""
read -p "Press Enter to link project (or Ctrl+C to exit)..."

vercel link

echo ""
echo "✅ Project linked!"
echo ""

# Get project info
PROJECT_NAME=$(vercel project ls 2>/dev/null | grep -m1 "llm" | awk '{print $1}' || echo "your-project")

echo "================================================"
echo "Step 2: Create Vercel Blob Storage"
echo "================================================"
echo ""
echo "⚠️  MANUAL STEP REQUIRED:"
echo ""
echo "1. Go to: https://vercel.com/dashboard"
echo "2. Select your project: $PROJECT_NAME"
echo "3. Click 'Storage' tab"
echo "4. Click 'Create Database'"
echo "5. Select 'Blob'"
echo "6. Name it: llmos-files"
echo "7. Click 'Create'"
echo ""
echo "After creation, copy the BLOB_READ_WRITE_TOKEN"
echo ""
read -p "Have you created Blob storage? (y/n) " -n 1 -r
echo ""

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "❌ Please create Blob storage first, then run this script again."
    exit 1
fi

echo ""
read -p "Enter your BLOB_READ_WRITE_TOKEN: " BLOB_TOKEN

if [ -z "$BLOB_TOKEN" ]; then
    echo "❌ No token provided. Exiting."
    exit 1
fi

echo "✅ Blob token received"

echo ""
echo "================================================"
echo "Step 3: Create Vercel KV (Redis) Storage"
echo "================================================"
echo ""
echo "⚠️  MANUAL STEP REQUIRED:"
echo ""
echo "1. Still in Vercel dashboard → Storage tab"
echo "2. Click 'Create Database' again"
echo "3. Select 'KV' (Redis)"
echo "4. Name it: llmos-sessions"
echo "5. Click 'Create'"
echo ""
echo "After creation, you'll see:"
echo "  - KV_REST_API_URL"
echo "  - KV_REST_API_TOKEN"
echo ""
read -p "Have you created KV storage? (y/n) " -n 1 -r
echo ""

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "❌ Please create KV storage first, then run this script again."
    exit 1
fi

echo ""
read -p "Enter your KV_REST_API_URL: " KV_URL
read -p "Enter your KV_REST_API_TOKEN: " KV_TOKEN

if [ -z "$KV_URL" ] || [ -z "$KV_TOKEN" ]; then
    echo "❌ Missing KV credentials. Exiting."
    exit 1
fi

echo "✅ KV credentials received"

echo ""
echo "================================================"
echo "Step 4: Add Environment Variables to Vercel"
echo "================================================"
echo ""

# Add environment variables
echo "Adding BLOB_READ_WRITE_TOKEN..."
vercel env add BLOB_READ_WRITE_TOKEN production <<< "$BLOB_TOKEN"
vercel env add BLOB_READ_WRITE_TOKEN preview <<< "$BLOB_TOKEN"
vercel env add BLOB_READ_WRITE_TOKEN development <<< "$BLOB_TOKEN"

echo ""
echo "Adding KV_REST_API_URL..."
vercel env add KV_REST_API_URL production <<< "$KV_URL"
vercel env add KV_REST_API_URL preview <<< "$KV_URL"
vercel env add KV_REST_API_URL development <<< "$KV_URL"

echo ""
echo "Adding KV_REST_API_TOKEN..."
vercel env add KV_REST_API_TOKEN production <<< "$KV_TOKEN"
vercel env add KV_REST_API_TOKEN preview <<< "$KV_TOKEN"
vercel env add KV_REST_API_TOKEN development <<< "$KV_TOKEN"

echo ""
echo "✅ Environment variables added to Vercel!"

echo ""
echo "================================================"
echo "Step 5: Create Local .env.local File"
echo "================================================"
echo ""

# Create .env.local for local development
cat > .env.local <<EOF
# Vercel Storage Credentials
# Generated by setup-vercel-storage.sh

# Blob Storage (for skills, workflows, files)
BLOB_READ_WRITE_TOKEN=$BLOB_TOKEN

# KV Storage (for sessions, messages)
KV_REST_API_URL=$KV_URL
KV_REST_API_TOKEN=$KV_TOKEN

# Your existing API key (replace with your actual key)
ANTHROPIC_API_KEY=sk-ant-api03-xxx...
EOF

echo "✅ Created .env.local with your credentials"
echo ""
echo "⚠️  IMPORTANT: .env.local is gitignored and will NOT be committed"

echo ""
echo "================================================"
echo "Step 6: Redeploy to Vercel"
echo "================================================"
echo ""
read -p "Deploy to production now? (y/n) " -n 1 -r
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Deploying to production..."
    vercel --prod
    echo ""
    echo "✅ Deployed!"
else
    echo "Skipping deployment. Run 'vercel --prod' when ready."
fi

echo ""
echo "================================================"
echo "✅ Setup Complete!"
echo "================================================"
echo ""
echo "Your storage is now configured:"
echo ""
echo "  📦 Vercel Blob   → Skills & files"
echo "  🔑 Vercel KV     → Sessions & messages"
echo "  📝 .env.local    → Local development"
echo ""
echo "Next steps:"
echo "  1. Test locally: npm run dev"
echo "  2. Test sessions: curl -X POST http://localhost:3000/api/sessions ..."
echo "  3. Test skills: curl -X POST http://localhost:3000/api/skills ..."
echo ""
echo "See VERCEL_SETUP.md for testing examples."
echo ""
