'use client';

import { useState, useEffect } from 'react';

/**
 * Analytics Dashboard
 *
 * Visualizes usage metrics, patterns, and insights from workspace activity.
 */

interface AnalyticsMetrics {
  sessions: {
    total: number;
    thisWeek: number;
    averageLength: number;
    trend: 'up' | 'down' | 'stable';
  };
  artifacts: {
    total: number;
    byType: Record<string, number>;
    thisWeek: number;
  };
  skills: {
    total: number;
    autoGenerated: number;
    mostUsed: Array<{ name: string; uses: number }>;
  };
  collaboration: {
    activeUsers: number;
    commits: number;
    pullRequests: number;
  };
  evolution: {
    patternsDetected: number;
    skillsGenerated: number;
    confidence: number;
  };
}

interface TimeSeriesData {
  date: string;
  sessions: number;
  artifacts: number;
  commits: number;
}

export default function AnalyticsDashboard() {
  const [metrics, setMetrics] = useState<AnalyticsMetrics | null>(null);
  const [timeSeries, setTimeSeries] = useState<TimeSeriesData[]>([]);
  const [timeRange, setTimeRange] = useState<'7d' | '30d' | '90d'>('7d');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadAnalytics();
  }, [timeRange]);

  const loadAnalytics = async () => {
    setLoading(true);

    try {
      // TODO: Replace with actual API call
      // Simulate API delay
      await new Promise(resolve => setTimeout(resolve, 500));

      // Mock data
      setMetrics({
        sessions: {
          total: 147,
          thisWeek: 23,
          averageLength: 12.5,
          trend: 'up',
        },
        artifacts: {
          total: 89,
          byType: {
            skills: 34,
            tools: 28,
            agents: 15,
            traces: 12,
          },
          thisWeek: 15,
        },
        skills: {
          total: 34,
          autoGenerated: 12,
          mostUsed: [
            { name: 'DCF Valuation', uses: 45 },
            { name: 'Contract Review', uses: 38 },
            { name: 'Data Analysis', uses: 31 },
          ],
        },
        collaboration: {
          activeUsers: 5,
          commits: 78,
          pullRequests: 12,
        },
        evolution: {
          patternsDetected: 8,
          skillsGenerated: 12,
          confidence: 0.87,
        },
      });

      setTimeSeries(generateMockTimeSeries(timeRange));
    } catch (error) {
      console.error('Failed to load analytics:', error);
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="h-full flex items-center justify-center bg-terminal-bg-secondary">
        <div className="text-terminal-accent-green animate-pulse">
          Loading analytics...
        </div>
      </div>
    );
  }

  if (!metrics) {
    return (
      <div className="h-full flex items-center justify-center bg-terminal-bg-secondary">
        <div className="text-terminal-fg-tertiary">
          No analytics data available
        </div>
      </div>
    );
  }

  return (
    <div className="h-full overflow-y-auto bg-terminal-bg-secondary p-6">
      {/* Header */}
      <div className="mb-6">
        <h1 className="terminal-heading text-xl mb-2">Analytics Dashboard</h1>
        <p className="text-sm text-terminal-fg-secondary">
          Insights and metrics from your workspace activity
        </p>
      </div>

      {/* Time Range Selector */}
      <div className="mb-6 flex gap-2">
        {(['7d', '30d', '90d'] as const).map((range) => (
          <button
            key={range}
            onClick={() => setTimeRange(range)}
            className={`
              px-4 py-2 rounded text-sm transition-colors
              ${
                timeRange === range
                  ? 'bg-terminal-accent-green text-terminal-bg-primary'
                  : 'bg-terminal-bg-tertiary text-terminal-fg-secondary hover:bg-terminal-bg-primary'
              }
            `}
          >
            {range === '7d' && 'Last 7 Days'}
            {range === '30d' && 'Last 30 Days'}
            {range === '90d' && 'Last 90 Days'}
          </button>
        ))}
      </div>

      {/* Metrics Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
        <MetricCard
          title="Sessions"
          value={metrics.sessions.total}
          subtitle={`${metrics.sessions.thisWeek} this week`}
          trend={metrics.sessions.trend}
          icon="💬"
        />
        <MetricCard
          title="Artifacts"
          value={metrics.artifacts.total}
          subtitle={`${metrics.artifacts.thisWeek} this week`}
          icon="📦"
        />
        <MetricCard
          title="Skills"
          value={metrics.skills.total}
          subtitle={`${metrics.skills.autoGenerated} auto-generated`}
          icon="⚡"
        />
        <MetricCard
          title="Active Users"
          value={metrics.collaboration.activeUsers}
          subtitle={`${metrics.collaboration.commits} commits`}
          icon="👥"
        />
      </div>

      {/* Charts Row */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">
        {/* Activity Timeline */}
        <div className="terminal-panel">
          <h3 className="terminal-heading text-sm mb-4">Activity Timeline</h3>
          <div className="h-48">
            <SimpleLineChart data={timeSeries} />
          </div>
        </div>

        {/* Artifact Distribution */}
        <div className="terminal-panel">
          <h3 className="terminal-heading text-sm mb-4">Artifact Distribution</h3>
          <div className="space-y-3">
            {Object.entries(metrics.artifacts.byType).map(([type, count]) => (
              <div key={type}>
                <div className="flex justify-between text-sm mb-1">
                  <span className="text-terminal-fg-primary capitalize">{type}</span>
                  <span className="text-terminal-fg-secondary">{count}</span>
                </div>
                <div className="w-full bg-terminal-bg-tertiary rounded-full h-2">
                  <div
                    className="bg-terminal-accent-green h-2 rounded-full transition-all"
                    style={{ width: `${(count / metrics.artifacts.total) * 100}%` }}
                  />
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Details Row */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Most Used Skills */}
        <div className="terminal-panel">
          <h3 className="terminal-heading text-sm mb-4">Most Used Skills</h3>
          <div className="space-y-3">
            {metrics.skills.mostUsed.map((skill, index) => (
              <div key={skill.name} className="flex items-center gap-3">
                <div className="text-2xl text-terminal-accent-yellow">
                  #{index + 1}
                </div>
                <div className="flex-1">
                  <div className="text-sm text-terminal-fg-primary">
                    {skill.name}
                  </div>
                  <div className="text-xs text-terminal-fg-tertiary">
                    {skill.uses} uses
                  </div>
                </div>
                <div className="w-16 bg-terminal-bg-tertiary rounded-full h-2">
                  <div
                    className="bg-terminal-accent-blue h-2 rounded-full"
                    style={{ width: `${(skill.uses / metrics.skills.mostUsed[0].uses) * 100}%` }}
                  />
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Evolution Insights */}
        <div className="terminal-panel">
          <h3 className="terminal-heading text-sm mb-4">Evolution Insights</h3>
          <div className="space-y-4">
            <div>
              <div className="text-sm text-terminal-fg-secondary mb-1">
                Patterns Detected
              </div>
              <div className="text-2xl text-terminal-accent-green">
                {metrics.evolution.patternsDetected}
              </div>
            </div>
            <div>
              <div className="text-sm text-terminal-fg-secondary mb-1">
                Skills Auto-Generated
              </div>
              <div className="text-2xl text-terminal-accent-blue">
                {metrics.evolution.skillsGenerated}
              </div>
            </div>
            <div>
              <div className="text-sm text-terminal-fg-secondary mb-1">
                Average Confidence
              </div>
              <div className="flex items-baseline gap-2">
                <div className="text-2xl text-terminal-accent-yellow">
                  {(metrics.evolution.confidence * 100).toFixed(0)}%
                </div>
                <div className="text-xs text-terminal-fg-tertiary">
                  (threshold: 85%)
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

/**
 * Metric Card Component
 */
function MetricCard({
  title,
  value,
  subtitle,
  trend,
  icon,
}: {
  title: string;
  value: number;
  subtitle: string;
  trend?: 'up' | 'down' | 'stable';
  icon: string;
}) {
  return (
    <div className="terminal-panel">
      <div className="flex items-start justify-between mb-2">
        <div className="text-xs text-terminal-fg-secondary">{title}</div>
        <div className="text-2xl">{icon}</div>
      </div>
      <div className="text-2xl text-terminal-fg-primary mb-1">{value}</div>
      <div className="flex items-center gap-2">
        <div className="text-xs text-terminal-fg-tertiary">{subtitle}</div>
        {trend && (
          <div className={`text-xs ${
            trend === 'up' ? 'text-terminal-accent-green' :
            trend === 'down' ? 'text-terminal-accent-red' :
            'text-terminal-fg-tertiary'
          }`}>
            {trend === 'up' && '↗'}
            {trend === 'down' && '↘'}
            {trend === 'stable' && '→'}
          </div>
        )}
      </div>
    </div>
  );
}

/**
 * Simple Line Chart Component
 */
function SimpleLineChart({ data }: { data: TimeSeriesData[] }) {
  if (data.length === 0) {
    return (
      <div className="h-full flex items-center justify-center text-terminal-fg-tertiary text-sm">
        No data available
      </div>
    );
  }

  const maxValue = Math.max(...data.map(d => Math.max(d.sessions, d.artifacts, d.commits)));
  const points = data.map((d, i) => ({
    x: (i / (data.length - 1)) * 100,
    sessions: ((d.sessions / maxValue) * 100),
    artifacts: ((d.artifacts / maxValue) * 100),
  }));

  return (
    <div className="relative h-full">
      {/* Y-axis labels */}
      <div className="absolute left-0 top-0 bottom-0 w-8 flex flex-col justify-between text-xs text-terminal-fg-tertiary">
        <div>{maxValue}</div>
        <div>{Math.round(maxValue / 2)}</div>
        <div>0</div>
      </div>

      {/* Chart area */}
      <div className="ml-10 h-full border-l border-b border-terminal-border relative">
        <svg className="w-full h-full" viewBox="0 0 100 100" preserveAspectRatio="none">
          {/* Sessions line */}
          <polyline
            points={points.map((p, i) => `${p.x},${100 - p.sessions}`).join(' ')}
            fill="none"
            stroke="var(--color-accent-primary)"
            strokeWidth="2"
            vectorEffect="non-scaling-stroke"
          />
          {/* Artifacts line */}
          <polyline
            points={points.map((p, i) => `${p.x},${100 - p.artifacts}`).join(' ')}
            fill="none"
            stroke="var(--color-accent-info)"
            strokeWidth="2"
            vectorEffect="non-scaling-stroke"
            strokeDasharray="4"
          />
        </svg>
      </div>

      {/* X-axis labels */}
      <div className="ml-10 mt-2 flex justify-between text-xs text-terminal-fg-tertiary">
        <div>{data[0]?.date}</div>
        <div>{data[Math.floor(data.length / 2)]?.date}</div>
        <div>{data[data.length - 1]?.date}</div>
      </div>

      {/* Legend */}
      <div className="ml-10 mt-4 flex gap-4 text-xs">
        <div className="flex items-center gap-2">
          <div className="w-3 h-0.5 bg-terminal-accent-green" />
          <span className="text-terminal-fg-secondary">Sessions</span>
        </div>
        <div className="flex items-center gap-2">
          <div className="w-3 h-0.5 bg-terminal-accent-blue" style={{ borderTop: '2px dashed' }} />
          <span className="text-terminal-fg-secondary">Artifacts</span>
        </div>
      </div>
    </div>
  );
}

/**
 * Generate mock time series data
 */
function generateMockTimeSeries(range: '7d' | '30d' | '90d'): TimeSeriesData[] {
  const days = range === '7d' ? 7 : range === '30d' ? 30 : 90;
  const data: TimeSeriesData[] = [];

  for (let i = 0; i < days; i++) {
    const date = new Date();
    date.setDate(date.getDate() - (days - i - 1));

    data.push({
      date: date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
      sessions: Math.floor(Math.random() * 20) + 5,
      artifacts: Math.floor(Math.random() * 15) + 3,
      commits: Math.floor(Math.random() * 10) + 1,
    });
  }

  return data;
}
