'use client';

import { useState } from 'react';
import ArtifactViewer, { ArtifactData, ViewMode } from './ArtifactViewer';

interface ArtifactGalleryProps {
  artifacts: Array<ArtifactData & { id: string }>;
  defaultView?: ViewMode;
}

/**
 * ArtifactGallery - Display multiple artifacts generated by workflow nodes
 *
 * Features:
 * - Grid or list view of artifacts
 * - Expandable artifact viewer
 * - Filter by artifact type
 * - Quick preview mode
 *
 * Usage:
 * ```tsx
 * <ArtifactGallery
 *   artifacts={[
 *     { id: '1', type: '3d-scene', data: sceneData },
 *     { id: '2', type: 'quantum-circuit', data: circuitData }
 *   ]}
 * />
 * ```
 */
export default function ArtifactGallery({
  artifacts,
  defaultView = 'graphical',
}: ArtifactGalleryProps) {
  const [selectedArtifact, setSelectedArtifact] = useState<string | null>(
    artifacts.length > 0 ? artifacts[0].id : null
  );
  const [filterType, setFilterType] = useState<string>('all');
  const [layoutMode, setLayoutMode] = useState<'grid' | 'list'>('list');

  // Filter artifacts by type
  const filteredArtifacts = artifacts.filter(
    (artifact) => filterType === 'all' || artifact.type === filterType
  );

  const selectedArtifactData = filteredArtifacts.find(
    (a) => a.id === selectedArtifact
  );

  // Get unique artifact types for filtering
  const artifactTypes = Array.from(
    new Set(artifacts.map((a) => a.type))
  );

  const getArtifactIcon = (type: string) => {
    switch (type) {
      case '3d-scene':
        return '🎨';
      case 'quantum-circuit':
        return '⚛️';
      case 'plot':
        return '📊';
      case 'code':
        return '💻';
      default:
        return '📄';
    }
  };

  const getArtifactLabel = (type: string) => {
    switch (type) {
      case '3d-scene':
        return '3D Scene';
      case 'quantum-circuit':
        return 'Quantum Circuit';
      case 'plot':
        return 'Plot';
      case 'code':
        return 'Code';
      default:
        return 'Artifact';
    }
  };

  if (artifacts.length === 0) {
    return (
      <div className="h-full flex items-center justify-center bg-terminal-bg-primary border border-terminal-border rounded">
        <div className="text-center text-terminal-fg-tertiary space-y-2">
          <div className="text-4xl">📦</div>
          <p className="text-sm">No artifacts generated yet</p>
          <p className="text-xs">Run a workflow to generate artifacts</p>
        </div>
      </div>
    );
  }

  return (
    <div className="h-full flex flex-col bg-terminal-bg-secondary">
      {/* Header with filters */}
      <div className="p-3 border-b border-terminal-border bg-terminal-bg-primary">
        <div className="flex items-center justify-between mb-2">
          <h3 className="terminal-heading text-xs">
            ARTIFACTS ({filteredArtifacts.length})
          </h3>
          <div className="flex gap-1">
            <button
              onClick={() => setLayoutMode('list')}
              className={`px-2 py-1 text-xs rounded ${
                layoutMode === 'list'
                  ? 'bg-terminal-accent-green text-terminal-bg-primary'
                  : 'bg-terminal-bg-secondary text-terminal-fg-secondary hover:bg-terminal-bg-tertiary'
              }`}
              title="List view"
            >
              ☰
            </button>
            <button
              onClick={() => setLayoutMode('grid')}
              className={`px-2 py-1 text-xs rounded ${
                layoutMode === 'grid'
                  ? 'bg-terminal-accent-green text-terminal-bg-primary'
                  : 'bg-terminal-bg-secondary text-terminal-fg-secondary hover:bg-terminal-bg-tertiary'
              }`}
              title="Grid view"
            >
              ⊞
            </button>
          </div>
        </div>

        {/* Type filters */}
        <div className="flex gap-1 overflow-x-auto">
          <button
            onClick={() => setFilterType('all')}
            className={`px-2 py-1 text-xs rounded whitespace-nowrap ${
              filterType === 'all'
                ? 'bg-terminal-accent-green text-terminal-bg-primary'
                : 'bg-terminal-bg-secondary text-terminal-fg-secondary hover:bg-terminal-bg-tertiary'
            }`}
          >
            All ({artifacts.length})
          </button>
          {artifactTypes.map((type) => (
            <button
              key={type}
              onClick={() => setFilterType(type)}
              className={`px-2 py-1 text-xs rounded whitespace-nowrap ${
                filterType === type
                  ? 'bg-terminal-accent-green text-terminal-bg-primary'
                  : 'bg-terminal-bg-secondary text-terminal-fg-secondary hover:bg-terminal-bg-tertiary'
              }`}
            >
              {getArtifactIcon(type)} {getArtifactLabel(type)} (
              {artifacts.filter((a) => a.type === type).length})
            </button>
          ))}
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 flex overflow-hidden">
        {/* Artifact list/grid */}
        <div
          className={`${
            layoutMode === 'list' ? 'w-48' : 'w-full'
          } border-r border-terminal-border overflow-auto p-2`}
        >
          {layoutMode === 'list' ? (
            <div className="space-y-2">
              {filteredArtifacts.map((artifact, idx) => (
                <button
                  key={artifact.id}
                  onClick={() => setSelectedArtifact(artifact.id)}
                  className={`w-full p-2 rounded text-left transition-all ${
                    selectedArtifact === artifact.id
                      ? 'bg-terminal-accent-green text-terminal-bg-primary'
                      : 'bg-terminal-bg-primary border border-terminal-border hover:border-terminal-accent-green text-terminal-fg-primary'
                  }`}
                >
                  <div className="flex items-center gap-2 mb-1">
                    <span>{getArtifactIcon(artifact.type)}</span>
                    <span className="text-xs font-medium">#{idx + 1}</span>
                  </div>
                  <div className="text-[10px] opacity-80">
                    {getArtifactLabel(artifact.type)}
                  </div>
                </button>
              ))}
            </div>
          ) : (
            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-2">
              {filteredArtifacts.map((artifact, idx) => (
                <button
                  key={artifact.id}
                  onClick={() => {
                    setSelectedArtifact(artifact.id);
                    setLayoutMode('list');
                  }}
                  className="p-3 rounded bg-terminal-bg-primary border border-terminal-border hover:border-terminal-accent-green transition-all text-center"
                >
                  <div className="text-2xl mb-1">
                    {getArtifactIcon(artifact.type)}
                  </div>
                  <div className="text-xs text-terminal-fg-primary">
                    #{idx + 1}
                  </div>
                  <div className="text-[10px] text-terminal-fg-secondary mt-1">
                    {getArtifactLabel(artifact.type)}
                  </div>
                </button>
              ))}
            </div>
          )}
        </div>

        {/* Artifact viewer */}
        {layoutMode === 'list' && selectedArtifactData && (
          <div className="flex-1 p-4 overflow-auto">
            <ArtifactViewer
              artifact={selectedArtifactData}
              defaultView={defaultView}
              height="100%"
            />
          </div>
        )}
      </div>
    </div>
  );
}
